# Generated by Django 4.1.1 on 2022-09-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=127, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=127, verbose_name='Last Name')),
                ('birth', models.DateField(verbose_name='Birthday')),
                ('email', models.EmailField(max_length=127, verbose_name='E-Mail')),
                ('nationality', models.TextField(max_length=63, verbose_name='Nationality')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse')], max_length=1)),
            ],
        ),
    ]
