# Generated by Django 4.1.1 on 2022-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
