# Generated by Django 4.1.1 on 2022-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicant_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth',
            field=models.DateField(verbose_name='Birthday YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(max_length=63, verbose_name='Nationality'),
        ),
    ]
