# Generated by Django 4.1.1 on 2022-09-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applicant_birth_alter_applicant_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='nation_other',
            field=models.CharField(blank=True, max_length=63, verbose_name='In case of nationality other then EWR+ please provide it here'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(choices=[('AUS', 'Austria'), ('BEL', 'Belgium'), ('BGR', 'Bulgaria'), ('CRO', 'Croatia'), ('CYP', 'Cyprus'), ('CZE', 'Czech Republic'), ('DNK', 'Denmark'), ('EST', 'Estonia'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Germany'), ('GRC', 'Greece'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IRE', 'Ireland'), ('ITA', 'Italy'), ('LVA', 'Latvia'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MAL', 'Malta'), ('NOR', 'Norway'), ('NLD', 'Netherlands'), ('POL', 'Poland'), ('POR', 'Portugal'), ('ROM', 'Romania'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SPA', 'Spain'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('OTH', 'Other')], max_length=3, verbose_name='Nationality'),
        ),
    ]
