# Generated by Django 4.1.1 on 2022-09-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applicant_nation_other_alter_applicant_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobtitle', models.CharField(max_length=127, verbose_name='Exact Job Title')),
                ('association', models.CharField(max_length=127, verbose_name='Trade association / Hazard tariff key')),
                ('hours', models.FloatField(verbose_name='Hours per week')),
                ('payrolltype', models.EmailField(choices=[('SAL', 'Salaried employee'), ('TRN', 'Trainee (salaried)'), ('MRH', 'Marginal help (salaried)'), ('SRT', 'Short term (salaried)'), ('WST', 'Working student'), ('COM', 'Commercial'), ('TRC', 'Trainee (commercial)'), ('MRC', 'Marginal help (commercial)'), ('SRC', 'Short term (commercial)')], max_length=3, verbose_name='Payroll type')),
                ('salary', models.FloatField(verbose_name='Salary')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default='1234', max_length=63, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
