# Generated by Django 4.1.1 on 2022-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_childrenproof_incometax_jobdates_socialsec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometax',
            name='bracket',
            field=models.CharField(blank=True, max_length=63, verbose_name='Tax bracket'),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='exempt_month',
            field=models.FloatField(blank=True, verbose_name='tax allowance per month'),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='exempt_year',
            field=models.FloatField(blank=True, verbose_name='tax allowance per year'),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='taxnum',
            field=models.CharField(blank=True, max_length=63, verbose_name='Tax identification number'),
        ),
    ]
