# Generated by Django 4.1.1 on 2022-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_incometax_bracket_alter_incometax_exempt_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboutline',
            name='payrolltype',
            field=models.CharField(choices=[('SAL', 'Salaried employee'), ('TRN', 'Trainee (salaried)'), ('MRH', 'Marginal help (salaried)'), ('SRT', 'Short term (salaried)'), ('WST', 'Working student'), ('COM', 'Commercial'), ('TRC', 'Trainee (commercial)'), ('MRC', 'Marginal help (commercial)'), ('SRC', 'Short term (commercial)')], max_length=3, verbose_name='Payroll type'),
        ),
    ]
