# Generated by Django 4.1.1 on 2022-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_joboutline_payrolltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdates',
            name='end',
            field=models.DateField(blank=True, verbose_name='End Date YYYY-MM-DD (if known)'),
        ),
    ]
