# Generated by Django 4.1.1 on 2022-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobdates_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdates',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End Date YYYY-MM-DD (if known)'),
        ),
        migrations.AlterField(
            model_name='socialsec',
            name='birthplace',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Birth name and Birthplace'),
        ),
        migrations.AlterField(
            model_name='socialsec',
            name='socialsec',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Social security number'),
        ),
    ]
