# Generated by Django 4.1.1 on 2022-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_jobdates_end_alter_socialsec_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometax',
            name='exempt_month',
            field=models.FloatField(blank=True, default=0.0, verbose_name='tax allowance per month'),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='exempt_year',
            field=models.FloatField(blank=True, default=0.0, verbose_name='tax allowance per year'),
        ),
    ]
